version: "3.1"

services:
  bot:
    image: docker.pkg.github.com/eyudinkov/kebab-bot/bot:latest
    depends_on:
      - mongo
    env_file:
      - ./.env
    logging:
      options:
        max-size: "1M"
        max-file: "10"

  mongo:
    image: mongo:4.2.15
    volumes:
      - /opt/mongo/data/db:/data/db
    env_file:
      - ./.env
    logging:
      options:
        max-size: "1M"
        max-file: "10"